[package]
name = "cores_of_cpu"
version = "0.1.0"
authors = ["Yu Zhao <{ID}+{username}@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"
